---
title: "Erasmus mobility EDA"
author: "Tamas Nagy"
date: '`r Sys.Date()`'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(countrycode)
library(tidytext)

theme_set(theme_light())

```

# Reading the data

```{r}
erasmus_raw <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-08/erasmus.csv')

custom_codes <- c("EL" = "Greece",
                  "UK" = "United Kingdom",
                  "XK" = "Kosovo")

erasmus <- 
  erasmus_raw %>% 
  mutate(sending_country = countrycode(sending_country_code, 
                                       origin = "iso2c",
                                       destination = "country.name", 
                                       custom_match = custom_codes),
         receiving_country = countrycode(receiving_country_code, 
                                       origin = "iso2c",
                                       destination = "country.name", 
                                       custom_match = custom_codes))

names(erasmus)
head(erasmus)

```

## Check academic year

```{r}
qplot(erasmus_raw$academic_year)

erasmus_raw %>% 
  ggplot() +
  aes(x = academic_year) +
  geom_bar() +
  scale_y_continuous(labels = scales::comma_format()) +
  labs(x = NULL, y = "Number of mobilities",
       title = "Number of mobilities over academic years")

```

## By participant gender
```{r}

erasmus_raw %>% 
  ggplot() +
  aes(x = academic_year, fill = participant_gender) +
  geom_bar() +
  scale_y_continuous(labels = scales::comma_format()) +
  labs(x = NULL, y = NULL,
       title = "Number of mobilities over academic years by gender",
       fill = "Participant gender")

```

# Countries

```{r}
erasmus %>% 
  count(sending_country, sort = TRUE) %>% 
  mutate(sending_country = fct_reorder(sending_country, n)) %>% 
  ggplot() +
  aes(y = sending_country, x = n) +
  geom_col()

erasmus %>% 
  select(sending_country, receiving_country) %>% 
  pivot_longer(everything(),
               names_to = "direction",
               values_to = "country") %>% 
  mutate(country = fct_lump(country, n = 25)) %>% 
  count(direction, country) %>% 
  mutate(country = reorder_within(country, n, direction),
         direction = str_remove(direction, "_country")) %>% 
  ggplot() +
  aes(y = country, x = n, fill = direction) +
  geom_col() +
  scale_y_reordered() +
  facet_wrap(~direction, scales = "free_y")


```

# Co-occurences

```{r}
erasmus %>% 
  mutate(sending_country = fct_lump(sending_country, n = 10)) %>% 
  mutate(receiving_country = fct_lump(receiving_country, n = 10)) %>% 
  count(sending_country, receiving_country) %>% 
  filter(sending_country != receiving_country) %>% 
  ggplot() +
  aes(y = sending_country, x = receiving_country, fill = log10(n)) +
  geom_tile() +
  labs(title = "Number of mobilities by sending and receiving country",
       x = NULL, y = NULL) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  
  
```

